import logging
import re
import time
from dataclasses import dataclass, fields
from textwrap import dedent
from string import Formatter
from typing import Optional

import requests

from mas_core.base_centralized_memory import BaseCentralizedMemory, Memory
from utils.message import MessageNode
from utils.stats import stats

logger = logging.getLogger(__name__)

EMPTY_MEMORY = ""

# Default vLLM API config
DEFAULT_API_BASE = "http://localhost:8100/v1"
DEFAULT_MODEL_NAME = "Qwen/Qwen3-4B-Instruct-2507"


@dataclass
class LLMAgent:
    # --- API settings ---
    api_base: str = DEFAULT_API_BASE
    model_name: str = DEFAULT_MODEL_NAME

    # Agent name
    role: Optional[str] = None
    # Agent UUID (autogenerated if not set)
    id: Optional[str] = None
    # Agent communication topology id in MAS
    topology_node_id: Optional[int] = None

    # --- System message settings ---
    system_prompt_template: Optional[str] = None
    system_prompt_role: str = "system"

    # --- User message settings ---
    user_prompt_template: Optional[str] = None
    user_prompt_role: str = "user"

    # --- Agent Memory ---
    centralized_memory: Optional[BaseCentralizedMemory] = None

    def invoke(
        self,
        system_batch_inputs: dict[str, list[str]],
        user_batch_inputs: dict[str, list[str]],
        generation_config: dict | None = None,
        **kwargs
    ) -> list[MessageNode]:
        """Invoke using OpenAI-compatible API on vLLM server."""
        if generation_config is None:
            generation_config = {}

        # Ensure generation_config is a dict (handle GenerationConfig object)
        if not isinstance(generation_config, dict):
            try:
                generation_config = vars(generation_config) if hasattr(generation_config, '__dict__') else {}
            except Exception:
                generation_config = {}

        batch_size = len(next(iter(system_batch_inputs.values())))

        batch_system_fields: list[dict] = []
        batch_user_fields: list[dict] = []
        message_nodes = []

        for i in range(batch_size):
            system_sample = {k: v[i] for k, v in system_batch_inputs.items()}
            user_sample = {k: v[i] for k, v in user_batch_inputs.items()}

            task_description = (
                user_sample.get("memory_task_description")
                or user_sample.get("task_description")
            )
            experience = self._trigger_memory(task_description)
            user_sample["memory_content"] = experience.text_memory
            user_sample["extra_fields"] = experience.extra_fields

            # construct the text prompt input for the LLM
            system_str, user_str = self._format_llm_input_prompt(
                system_fields=system_sample,
                user_fields=user_sample
            )

            # Call API
            output_str = self._call_api(system_str, user_str, generation_config)

            node = MessageNode(
                system_prompt_template=self.system_prompt_template,
                system_prompt_fields=system_sample,
                user_prompt_template=self.user_prompt_template,
                user_prompt_fields=user_sample,
                formatted_system_prompt=system_str,
                formatted_user_prompt=user_str,
                response=output_str,
                state=self._state
            )
            message_nodes.append(node)

        return message_nodes

    def _call_api(
        self,
        system_prompt: str,
        user_prompt: str,
        generation_config: dict | object,
        retry_count: int = 2,
        max_input_chars: int = 120000,
    ) -> str:
        """Call the vLLM OpenAI-compatible chat completions API."""
        # Handle both dict and GenerationConfig object
        if not isinstance(generation_config, dict):
            # Convert GenerationConfig or other objects to dict
            try:
                generation_config = vars(generation_config) if hasattr(generation_config, '__dict__') else {}
            except Exception:
                generation_config = {}

        # Truncate oversized prompts to avoid exceeding max-model-len.
        max_tokens_out = generation_config.get("max_new_tokens", 4096)
        if len(system_prompt) + len(user_prompt) > max_input_chars:
            budget = max_input_chars
            sys_budget = min(len(system_prompt), budget // 4)
            usr_budget = budget - sys_budget
            if len(system_prompt) > sys_budget:
                system_prompt = system_prompt[:sys_budget] + "\n...[truncated]"
            if len(user_prompt) > usr_budget:
                user_prompt = user_prompt[:usr_budget] + "\n...[truncated]"
            logger.warning(
                f"Prompt truncated to ~{max_input_chars} chars to fit context window"
            )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]

        payload = {
            "model": self.model_name,
            "messages": messages,
            "temperature": generation_config.get("temperature", 0.7),
            "top_p": generation_config.get("top_p", 0.9),
            "max_tokens": max_tokens_out,
        }

        stop = generation_config.get("stop_strings")
        if stop:
            payload["stop"] = stop

        url = f"{self.api_base}/chat/completions"

        for attempt in range(1 + retry_count):
            try:
                t0 = time.time()
                response = requests.post(url, json=payload, timeout=120.0)
                response.raise_for_status()
                elapsed = time.time() - t0
                data = response.json()
                content = data["choices"][0]["message"]["content"]
                # Strip <think>...</think> tags if present (Qwen3 thinking mode)
                content = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()
                # Record stats
                usage = data.get("usage", {})
                stats.record(
                    source=f"agent/{self.role or 'unknown'}",
                    prompt_tokens=usage.get("prompt_tokens", 0),
                    completion_tokens=usage.get("completion_tokens", 0),
                    elapsed=elapsed,
                )
                return content
            except requests.exceptions.HTTPError as e:
                if e.response is not None and e.response.status_code == 400:
                    logger.warning("API returned 400 (prompt too long?). Returning empty response.")
                    return ""
                logger.warning(f"API call attempt {attempt + 1} failed: {e}")
                if attempt < retry_count:
                    time.sleep(1)
                else:
                    logger.error(f"API call failed after {1 + retry_count} attempts. Returning empty response.")
                    return ""
            except Exception as e:
                logger.warning(f"API call attempt {attempt + 1} failed: {e}")
                if attempt < retry_count:
                    time.sleep(1)
                else:
                    logger.error(f"API call failed after {1 + retry_count} attempts. Returning empty response.")
                    return ""

    @property
    def _state(self) -> dict:
        state = {}
        for field_name, value in self.__dict__.items():
            if field_name in ["centralized_memory"]:
                if value is None:
                    state[field_name] = None
                else:
                    state[field_name] = str(type(value).__name__)
            else:
                state[field_name] = value
        return state

    def _reconstruct_state(self, state: dict):
        for f in fields(self):
            if f.name not in ["centralized_memory"]:
                setattr(self, f.name, state.get(f.name))

    def _trigger_memory(self, task_description: str) -> Memory:
        if self.centralized_memory is not None:
            memory = self.centralized_memory.retrieve_memory(task_description, self)
            if memory.text_memory is None:
                memory.text_memory = EMPTY_MEMORY
        else:
            memory = Memory(text_memory=EMPTY_MEMORY)
        return memory

    def _safe_format(self, template: str, fields: dict) -> str:
        template = dedent(template)
        formatter = Formatter()
        field_names = {fname for _, fname, _, _ in formatter.parse(template) if fname}

        missing_fields = field_names - fields.keys()
        if missing_fields:
            raise KeyError(f"Missing fields for formatting: {missing_fields}")

        safe_fields = {k: v for k, v in fields.items() if k in field_names}
        return template.format(**safe_fields)

    def _prepare_prompt_fields(self, fields: dict) -> dict:
        prepared = {}
        for key, value in fields.items():
            if value is None:
                prepared[key] = ""
            elif isinstance(value, str):
                text = value.strip()
                prepared[key] = "" if text == EMPTY_MEMORY else text
            else:
                prepared[key] = value

        prepared.setdefault(
            "memory_block",
            self._section_block("Retrieved Content", prepared.get("memory_content", "")),
        )

        function_name = str(prepared.get("function_name", "")).strip()
        prepared.setdefault(
            "function_name_block",
            self._section_block(
                "Function Name",
                f"Use exactly `{function_name}`." if function_name else "",
            ),
        )
        return prepared

    def _section_block(self, title: str, content: str) -> str:
        text = str(content or "").strip()
        if not text:
            return ""
        return f"# {title}\n{text}"

    def _compact_prompt(self, prompt: str) -> str:
        prompt = dedent(prompt)
        prompt = re.sub(r"\r\n?", "\n", prompt)
        prompt = "\n".join(line.rstrip() for line in prompt.splitlines())
        prompt = re.sub(
            r"(?ms)^[ \t]*#{1,6}[^\n]*\n(?:[ \t]*\n)*(?=^[ \t]*#{1,6}\s|\Z)",
            "",
            prompt,
        )
        prompt = re.sub(r"\n{3,}", "\n\n", prompt)
        return prompt.strip()

    def _format_llm_input_prompt(self, system_fields: dict, user_fields: dict) -> tuple[str, str]:
        """Safely format system and user prompts."""
        system_fields = self._prepare_prompt_fields(system_fields)
        user_fields = self._prepare_prompt_fields(user_fields)
        system_prompt = self._compact_prompt(
            self._safe_format(self.system_prompt_template, system_fields)
        )
        user_prompt = self._compact_prompt(
            self._safe_format(self.user_prompt_template, user_fields)
        )
        return system_prompt, user_prompt
