#!/usr/bin/env python3
"""
Vector retrieval service for TriviaQA and PopQA.

Supported document sources:
1. `*_docs.pkl` files generated by the local index builders.
2. Search-R1 / FlashRAG-style `wiki-18.jsonl(.gz)` corpora.

Supported encoders:
1. OpenAI-compatible embedding APIs.
2. A local Hugging Face dense retriever when no embedding service is available.

The service listens on 127.0.0.1:8001/retrieve by default.
"""
import argparse
import sys
import os
from typing import List

try:
    from flask import Flask, request, jsonify
except ModuleNotFoundError:
    Flask = None
    request = None
    jsonify = None

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from dotenv import load_dotenv
load_dotenv(os.path.join(PROJECT_ROOT, ".env"))

from common.utils.retrieval_corpus import DocumentStore, resolve_query_prefix


def _resolve_local_snapshot(model_name_or_path: str) -> str:
    if not model_name_or_path:
        return model_name_or_path
    if os.path.exists(model_name_or_path):
        return model_name_or_path

    hf_home = os.getenv("HF_HOME") or os.getenv("TRANSFORMERS_CACHE")
    if not hf_home:
        return model_name_or_path

    cache_entry = os.path.join(hf_home, f"models--{model_name_or_path.replace('/', '--')}")
    refs_main = os.path.join(cache_entry, "refs", "main")
    snapshots_dir = os.path.join(cache_entry, "snapshots")

    if os.path.isfile(refs_main):
        with open(refs_main, "r", encoding="utf-8") as handle:
            revision = handle.read().strip()
        if revision:
            candidate = os.path.join(snapshots_dir, revision)
            if os.path.isdir(candidate):
                return candidate

    if os.path.isdir(snapshots_dir):
        snapshots = sorted(
            os.path.join(snapshots_dir, item)
            for item in os.listdir(snapshots_dir)
            if os.path.isdir(os.path.join(snapshots_dir, item))
        )
        if snapshots:
            return snapshots[-1]
    return model_name_or_path


class EmbeddingClient:
    """Embedding client supporting API mode and local HF encoder mode."""
    def __init__(self, base_url: str = None, api_key: str = None, model: str = None, embed_dim: int = None):
        # Prefer explicit arguments, then environment variables. An empty base URL selects local mode.
        self.base_url = (base_url if base_url is not None else os.getenv("EMBED_BASE_URL", "")).strip()
        self.api_key = api_key or os.getenv("EMBED_API_KEY")
        self.model = model or os.getenv("EMBED_MODEL", "intfloat/e5-base-v2")
        self.embed_dim = embed_dim or int(os.getenv("EMBED_DIM", "0")) or None
        self.mode = "api" if self.base_url else "local"
        self._tokenizer = None
        self._model = None
        self._torch = None

        if self.mode == "api":
            import requests
            self.requests = requests
        else:
            import torch
            from transformers import AutoModel, AutoTokenizer

            self._torch = torch
            self._auto_model = AutoModel
            self._auto_tokenizer = AutoTokenizer
            self.device = "cuda" if torch.cuda.is_available() else "cpu"
            self.model_path = _resolve_local_snapshot(self.model)

    def _load_local_model(self):
        if self._model is not None and self._tokenizer is not None:
            return
        self._tokenizer = self._auto_tokenizer.from_pretrained(
            self.model_path,
            trust_remote_code=True,
            local_files_only=os.path.exists(self.model_path),
        )
        self._model = self._auto_model.from_pretrained(
            self.model_path,
            trust_remote_code=True,
            local_files_only=os.path.exists(self.model_path),
        )
        self._model.eval()
        self._model.to(self.device)

    def _embed_via_api(self, texts: List[str]):
        import numpy as np

        headers = {"Content-Type": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"

        # SiliconFlow follows an OpenAI-compatible embedding schema.
        payload = {
            "input": texts,
            "model": self.model
        }
        if self.embed_dim:
            payload["dimensions"] = self.embed_dim
        
        response = self.requests.post(
            f"{self.base_url}/embeddings",
            json=payload,
            headers=headers
        )
        response.raise_for_status()
        data = response.json()
        
        # Handle common API response variants.
        if "data" in data:
            embeddings = [item["embedding"] for item in data["data"]]
        else:
            # Some APIs return the embedding list directly.
            embeddings = data.get("embeddings", [])

        return np.array(embeddings, dtype=np.float32)

    def _embed_locally(self, texts: List[str]):
        import numpy as np

        self._load_local_model()
        inputs = self._tokenizer(
            texts,
            max_length=256,
            padding=True,
            truncation=True,
            return_tensors="pt",
        )
        inputs = {key: value.to(self.device) for key, value in inputs.items()}

        with self._torch.no_grad():
            outputs = self._model(**inputs, return_dict=True)
            if getattr(outputs, "pooler_output", None) is not None:
                pooled = outputs.pooler_output
            else:
                hidden = outputs.last_hidden_state.masked_fill(
                    ~inputs["attention_mask"][..., None].bool(), 0.0
                )
                pooled = hidden.sum(dim=1) / inputs["attention_mask"].sum(dim=1)[..., None]
            pooled = self._torch.nn.functional.normalize(pooled, dim=-1)
        return pooled.detach().cpu().numpy().astype(np.float32)

    def embed(self, texts: List[str]):
        """Return embedding vectors for a batch of texts."""
        if self.mode == "api":
            return self._embed_via_api(texts)
        return self._embed_locally(texts)


class RetrievalServer:
    def __init__(
        self,
        index_path: str,
        embed_url: str = None,
        api_key: str = None,
        model: str = None,
        corpus_path: str | None = None,
        query_prefix: str = "",
    ):
        if Flask is None:
            print("Please install Flask for the retrieval service: pip install Flask")
            sys.exit(1)

        self.app = Flask(__name__)
        self.query_prefix = query_prefix or ""
        
        # Load the FAISS index.
        try:
            import faiss
            self.faiss = faiss
        except ImportError:
            print("Please install faiss: pip install faiss-cpu")
            sys.exit(1)
        
        print(f"Loading index: {index_path}")
        self.index = faiss.read_index(index_path)
        
        # Load the document map or an external JSONL corpus.
        self.documents = DocumentStore(index_path=index_path, corpus_path=corpus_path)
        print(f"Document source: {self.documents.mode} ({self.documents.source_path})")
        print(f"Loaded {len(self.documents)} documents")
        
        # Embedding client, using either an API endpoint or a local model.
        self.embed_client = EmbeddingClient(embed_url, api_key, model)
        probe = self.embed_client.embed(
            [f"{self.query_prefix}dimension sanity probe" if self.query_prefix else "dimension sanity probe"]
        )
        if probe.shape[1] != self.index.d:
            raise RuntimeError(
                f"Embedding dim mismatch: model {self.embed_client.model} outputs "
                f"{probe.shape[1]}-d vectors but FAISS index expects {self.index.d}-d. "
                f"Rebuild the index with the same model, or point to a compatible model."
            )
        if self.embed_client.mode == "api":
            print(
                f"Using embedding API: {self.embed_client.base_url}, model={self.embed_client.model}, "
                f"dim={probe.shape[1]}, query_prefix={self.query_prefix!r}"
            )
        else:
            print(
                f"Using local embedding model: {getattr(self.embed_client, 'model_path', self.embed_client.model)}, "
                f"device={self.embed_client.device}, dim={probe.shape[1]}, query_prefix={self.query_prefix!r}"
            )
        
        # Register routes.
        self.app.route('/retrieve', methods=['POST'])(self.retrieve)
        self.app.route('/health', methods=['GET'])(self.health)
    
    def health(self):
        return jsonify({
            "status": "ok",
            "docs_count": len(self.documents),
            "query_prefix": self.query_prefix,
            "doc_source_mode": self.documents.mode,
        })
    
    def retrieve(self):
        """POST /retrieve endpoint."""
        data = request.get_json()
        queries = data.get("queries", [])
        topk = data.get("topk", 3)
        return_scores = data.get("return_scores", True)
        
        if not queries:
            return jsonify({"error": "No queries provided"}), 400
        
        embed_inputs = (
            [f"{self.query_prefix}{q}" for q in queries]
            if self.query_prefix else list(queries)
        )

        # Encode queries.
        query_embeddings = self.embed_client.embed(embed_inputs)
        
        # L2-normalize vectors for cosine similarity.
        self.faiss.normalize_L2(query_embeddings)
        
        # Search nearest neighbors.
        scores, indices = self.index.search(query_embeddings, topk)
        
        # Build response payload.
        results = []
        for i, query in enumerate(queries):
            query_results = []
            for j, (score, idx) in enumerate(zip(scores[i], indices[i])):
                if idx < 0 or idx >= len(self.documents):
                    continue
                doc = self.documents.get(int(idx))
                result = {
                    "document": doc,
                    "score": float(score)
                }
                query_results.append(result)
            results.append(query_results)
        
        return jsonify({
            "result": results,
            "queries": queries,
            "topk": topk
        })
    
    def run(self, host: str = "127.0.0.1", port: int = 8001):
        print(f"Retrieval service started: http://{host}:{port}/retrieve")
        print(f"Health check: http://{host}:{port}/health")
        self.app.run(host=host, port=port, threaded=True)


def main():
    parser = argparse.ArgumentParser(description="Vector retrieval service with API or local embeddings")
    parser.add_argument("--index", type=str, default="./data/triviaqa/index.faiss",
                        help="Path to the FAISS index file")
    parser.add_argument("--corpus-path", type=str, default=None,
                        help="Path to a Search-R1 / FlashRAG-style JSONL corpus; required when no *_docs.pkl exists")
    parser.add_argument("--embed-url", type=str, default=None,
                        help="Embedding API URL (defaults to EMBED_BASE_URL)")
    parser.add_argument("--api-key", type=str, default=None,
                        help="Embedding API key (defaults to EMBED_API_KEY)")
    parser.add_argument("--model", type=str, default=None,
                        help="Embedding model name (defaults to EMBED_MODEL)")
    parser.add_argument("--query-prefix", type=str,
                        default=os.getenv("RETRIEVAL_QUERY_PREFIX", ""),
                        help="Fixed prefix prepended to every query. Search-R1 / e5-base-v2 commonly uses 'query: '")
    parser.add_argument("--host", type=str, default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8001,
                        help="Retrieval service port; keep it separate from LLM and embedding service ports")
    args = parser.parse_args()
    
    if not os.path.exists(args.index):
        print(f"Error: index file does not exist: {args.index}")
        print("Build an index first, for example: python scripts/build_triviaqa_index.py")
        sys.exit(1)
    
    query_prefix = resolve_query_prefix(args.model or os.getenv("EMBED_MODEL", ""), args.query_prefix)
    if query_prefix and not args.query_prefix:
        print(f"Auto-detected dense retriever prefix: {query_prefix!r}")

    server = RetrievalServer(
        args.index,
        args.embed_url,
        args.api_key,
        args.model,
        corpus_path=args.corpus_path,
        query_prefix=query_prefix,
    )
    server.run(args.host, args.port)


if __name__ == "__main__":
    main()
